version: '3.8'

services:
  nodejs-api:
    image: user-ms:latest
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: water company

  mysql:
    image: mysql:latest
    ports:
      - "8080:80"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: water company
    volumes:
      - C:\Users\zarro\Downloads\water_company (1).sql:/docker-entrypoint-initdb.d/water_company.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "3306:3306"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD:
